---
name: "Auto Merge Dependabot PRs"
"on":
  pull_request:
    types:
    - "labeled"
    - "opened"
    - "synchronize"
jobs:
  auto-merge:
    if: "${{ github.actor == 'dependabot[bot]' }} || ${{ github.actor == 'BenSlabbert'\
      \ }}"
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"
    - name: "Auto-merge Dependabot PRs"
      run: "PR_LABEL=$(gh pr view ${{ github.event.pull_request.number }} --json labels\
        \ --jq '.labels[].name' | grep -i 'automerge')\nif [ \"$PR_LABEL\" == \"automerge\"\
        \ ]; then\n  gh pr merge ${{ github.event.pull_request.number }} --rebase\
        \ --auto\nfi\n"
